### ISSUE TITLE
How do i create a new world?

### ISSUE THREAD

**Issue by spocane** [MysteriousAges/SimpleDim#3]
I am having troubles finding where to put my new dim config at.

here is my dim config

"TestLand{ id: -10; type: superflat; generator: "2;7,4x159:15,55x159;1"; spawn: (0, 50, 0) }"

I need to know what file or command that you need to put this in and what format.

Thanks

**Comment by MysteriousAges** [comment]
Put it in a file with a .cfg extension in the folder configs/XCompCraft - That's where all the configs will be read from. You can have multiple files, or a single cfg file in a pack.

**Comment by spocane** [comment]
I figured it was easy and I was just missing a step somewhere. Thank you

**Comment by MysteriousAges** [comment]
Don't forget you'll either need to provide a command block to teleport players to/from the dimenison, or specify a teleporter item in the same configs.

**Comment by spocane** [comment]
I got the Dimensions to work, but am having difficulty with the item.

this is what i am trying:

"item Teleporter { forDimension: TestLand; type: accessCard; displayName: "Transport to TestLand" }"

this just crashed the game with: http://pastebin.com/vPcWLf7g

**Comment by MysteriousAges** [comment]
Ah, right. You need to specify at least one colour for the item. I'll update the docs.
