### ISSUE TITLE
Beta3 Superflat

### ISSUE THREAD

**Issue by Thiana** [MysteriousAges/SimpleDim#5]
![2015-09-10_20 02 14](https://cloud.githubusercontent.com/assets/405832/9804014/e2a93a22-57f6-11e5-97a2-a4114ccc9f35.png)

The above should be a superflat Extreme Hills, instead its an odd mix of Forest/Plains/Swampland with _clouds_ at y=4.

Config:

---

dimMiningAge { id: 7; type: superflat; generator: "3;1_minecraft:bedrock,64_minecraft:stone,3_minecraft:dirt,1_minecraft:grass;3;decoration" }
item Mining Age Access Card { forDimension: dimMiningAge; type: accessCard; colours: [0xffffff, 0x000000, 0xa335ee]; displayName: acMiningAge }

---

Thanks.

**Comment by MysteriousAges** [comment]
You're using a version of the generator that isn't supported in 1.7. If you're getting the string from a site, make sure it supports 1.7, and that the string begins with "2;". This means that the generator is using version 2 (which 1.7 and 1.8 supports).

**Comment by Thiana** [comment]
You may want to update the readme with a new link (http://www.minecraft101.net/superflat_legacy/) then. I was using http://www.minecraft101.net/superflat/ as suggested :)

**Comment by MysteriousAges** [comment]
OPPS. I'll fix that up right now...

**Comment by Thiana** [comment]
Getting closer. Using:

---

dimMiningAge { id: 7; type: superflat; generator: "2;1x7,64x1,7x3,1x2;3;decoration" }
item Mining Age Access Card { forDimension: dimMiningAge; type: accessCard; colours: [0xffffff, 0x000000, 0xa335ee]; displayName: acMiningAge }

---

I get a superflat that is usable for mining, but its' not extreme hills. Instead I seem to get a flat version of normal overworld biomes. You can see Plains, Forest, River and Extreme Hills in this image.

![2015-09-10_20 46 57](https://cloud.githubusercontent.com/assets/405832/9804578/556564a4-57fd-11e5-8da8-48d6786b9e4c.png)

PS: There is no option to reopen this issue, only a 'Comment'. Maybe you have to configure it to allow reopening issues?
