### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by ghost** [MysteriousAges/SimpleDim#7]
I was wondering if it would be possible for you to add a new type of dimension. Cave world. If its not thank you for your time anyway :)

**Comment by MysteriousAges** [comment]
I'd rather not add worldgen types to this mod specifically, and rather do it by way of compatibility with existing worldgen mods.
Are there any cave world type mods you know of I could do this with?

**Comment by ghost** [comment]
I know that epic siege mode mod has a cave  world but I have no clue how they do it.

**Comment by ghost** [comment]
And sorry it took me so long to respond.
